---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    exclude_fingerprints:
    - bf8f1f256605f0d32c60b8cb6aaebed7
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
